### PR TITLE
Add **kwargs to actions for use with nested routers

### PR DESCRIPTION
**Pull request by jzmiller1**
Add **kwargs so the endpoints can be used with nested routers from: https://github.com/alanjds/drf-nested-routers

### CODE REVIEW

**Review by banesullivan — APPROVED** [review]
I'm not totally sure how all this works with nested routers, but happy to merge this and cut a release for you.

I don't *love* unused `kwargs` in APIs but having these on the REST methods themselves seems appropriate

----

On a separate note, @jzmiller1, I'd love to gain some insight on how you are using this package? Are you working with geospatial imagery? or other types of large images? Are you working on an open source project or something else? Any insight would be greatly appreciated!

**Comment by banesullivan** [comment]
`0.8.2` is released with these additions: https://pypi.org/project/django-large-image/

**Comment by jzmiller1** [comment]
> I'm not totally sure how all this works with nested routers, but happy to merge this and cut a release for you.

we have some endpoints that are structured like: api/item/<item_pk>/subitem/<subitem_pk>/  so the drf nested router passes both item_pk and subitem_pk and having **kwargs lets us catch the unused item_pk

> On a separate note, @jzmiller1, I'd love to gain some insight on how you are using this package? Are you working with geospatial imagery? or other types of large images? Are you working on an open source project or something else? Any insight would be greatly appreciated!

We are working with geospatial imagery.  This looked like a great way to quickly plug tiles and thumbnails in from COG.  The project that led me here is not open source but I do a good bit with geospatial imagery so I'm likely to use it for other things as well.

**Comment by banesullivan** [comment]
Awesome, I'm happy to see more people outside our organization using this!

**Pull request merged**
